// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU-4Z6QS7ocPOqc_dVdidwtV6qYp9eIxQ',
    appId: '1:755491305026:web:380ab664a681a0495adfdb',
    messagingSenderId: '755491305026',
    projectId: 'aluna-app2025',
    authDomain: 'aluna-app2025.firebaseapp.com',
    storageBucket: 'aluna-app2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXQh-6WB7U41VybMIZkGo5v9FikkL2weE',
    appId: '1:755491305026:android:a55c346610aec5ef5adfdb',
    messagingSenderId: '755491305026',
    projectId: 'aluna-app2025',
    storageBucket: 'aluna-app2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzU0vgNlfZeFbzpKaQnaQgZyzvnvv4iRo',
    appId: '1:755491305026:ios:4c8d6e49648754ee5adfdb',
    messagingSenderId: '755491305026',
    projectId: 'aluna-app2025',
    storageBucket: 'aluna-app2025.firebasestorage.app',
    iosBundleId: 'com.example.alunaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzU0vgNlfZeFbzpKaQnaQgZyzvnvv4iRo',
    appId: '1:755491305026:ios:4c8d6e49648754ee5adfdb',
    messagingSenderId: '755491305026',
    projectId: 'aluna-app2025',
    storageBucket: 'aluna-app2025.firebasestorage.app',
    iosBundleId: 'com.example.alunaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU-4Z6QS7ocPOqc_dVdidwtV6qYp9eIxQ',
    appId: '1:755491305026:web:ba5979d5600179865adfdb',
    messagingSenderId: '755491305026',
    projectId: 'aluna-app2025',
    authDomain: 'aluna-app2025.firebaseapp.com',
    storageBucket: 'aluna-app2025.firebasestorage.app',
  );
}
