name: aluna
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.3
  dio: ^5.7.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  form_field_validator: ^1.1.0
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  health: ^13.1.1
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.4
  permission_handler: ^11.4.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.0+3
  speech_to_text: ^7.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/Cairo-Regular.ttf 

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/tokenizer/tokenizer.json
